#!/bin/bash

#PBS -N step-32
#PBS -l walltime=00:05:00
#PBS -l nodes=OOOOO:ppn=20
#PBS -q regular
#PBS -M mbarde@sissa.it
#PBS -m abe

nodes=OOOOO
BUILD_DIR="build_"$nodes
OUTPUT="../output_09.data"

cd "$PBS_O_WORKDIR"
cd ..
mkdir $BUILD_DIR
cd $BUILD_DIR

source /home/mbarde/opt/module.conf

let p=$nodes*20

cmake ..
make -j$p step-32


mpirun -np $p ./step-32 ../apps/step-32.prm
RESULT="$( mpirun -np $p ./step-32 ../apps/step-32.prm)"

DOF=$(	echo "$RESULT" |\
	grep "Number of degrees of freedom" |\
	cut -d" "  -f6| xargs)

LOP=$( echo "$RESULT" |\
        grep "LO" |\
        cut -d'|' -f4 |\
        sed 's#s###'| xargs)

RAW=$( echo "$RESULT" |\
	grep "raw" |\
	head -1 |\
        cut -d'|' -f4 |\
        sed 's#s###'| xargs)

RAWO=$( echo "$RESULT" |\
        grep "raw opt" |\
        cut -d'|' -f4 |\
        sed 's#s###'| xargs)

echo "================================================" >> ${OUTPUT}_bkp
echo "np="$p >> ${OUTPUT}_bkp
echo "$RESULT" >> ${OUTPUT}_bkp
printf "%10d %10d %20f %20f %20f\n" $p $DOF $LOP $RAW $RAWO >> ${OUTPUT}
